name: Build and Setup Eth Analysis Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Rust environment
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.82.0"
          override: true

      # Step 3: Install dependencies (if needed, for example, installing `git` or other dependencies)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config build-essential

      # Step 4: Install Lighthouse (Beacon Node)
#      - name: Install Lighthouse beacon node
#        run: |
#          git clone https://github.com/sigp/lighthouse.git
#          cd lighthouse
#          make

      # Step 5: Start the beacon node locally (in the background)
#      - name: Start Lighthouse beacon node
#        run: |
#          cd lighthouse
#          nohup ./target/release/lighthouse bn --network mainnet --http > beacon.log 2>&1 &
#
#          # Wait for a few seconds to allow the node to start
#          sleep 10
#          # Check if the Lighthouse node is running by hitting its API endpoint
#          for i in {1..60}; do
#            if curl -s http://localhost:5052/eth/v1/node/syncing | grep -q 'is_syncing'; then
#              echo "Beacon node is running!"
#              exit 0
#            fi
#            echo "Waiting for beacon node... (attempt $i)"
#            sleep 1
#          done
#          echo "Beacon node failed to start within 60 seconds."
#          exit 1

      # Step 6: Build Rust project
      - name: Build Rust project
        run: RUSTFLAGS="-Awarnings" cargo build

#      # Step 7: Run tests (if any tests are in place)
#      - name: Run tests
#        run: RUSTFLAGS="-Awarnings" cargo test --verbose -- --nocapture