name: Build and Setup Eth Analysis Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-setup:
    name: Setup Services
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: defaultdb
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.82.0"
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config build-essential

      - name: Install Cargo Sqlx
        run: cargo install sqlx-cli

      - name: Apply database migrations
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/defaultdb"
        run: cargo sqlx migrate run

      - name: Build Rust project
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/defaultdb"
        run: cargo build

      - name: Show migrations in database
        run: |
          PGPASSWORD=admin psql -h localhost -U admin -d defaultdb -c "SELECT * FROM __sqlx_migrations;"

